version: "3"

services: 
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/app

  mysql:
    container_name: db
    restart: always
    image: mysql:5.7
    ports:
      - 3308:3306
    volumes:
      - doctors-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: "gcb-test"

volumes:
  doctors-mysql: